<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1.2 (Python 3.9.6 on darwin)" generated="20220209 11:28:16.053" rpa="false" schemaversion="2">
<suite id="s1" name="Buy Auto Convencional" source="/Users/laylla.rodrigues/security_robot/automation/specs/buy_auto_convencional.robot">
<test id="s1-t1" name="Preenchendo cotação">
<kw name="Nova sessão auto" type="SETUP">
<msg timestamp="20220209 11:28:16.680" level="FAIL">No keyword with name 'Nova sessão auto' found.</msg>
<status status="FAIL" starttime="20220209 11:28:16.680" endtime="20220209 11:28:16.680"/>
</kw>
<status status="FAIL" starttime="20220209 11:28:16.673" endtime="20220209 11:28:16.680">Setup failed:
No keyword with name 'Nova sessão auto' found.</status>
</test>
<status status="FAIL" starttime="20220209 11:28:16.055" endtime="20220209 11:28:16.681"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Buy Auto Convencional">Buy Auto Convencional</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220209 11:28:16.088" level="ERROR">Error in file '/Users/laylla.rodrigues/security_robot/automation/specs/buy_auto_convencional.robot' on line 2: Resource file '/Users/laylla.rodrigues/security_robot/automation/specs/resources/Base.robot' does not exist.</msg>
</errors>
</robot>
